### ISSUE TITLE
v2.1 roadmap

### ISSUE THREAD

**Issue by fabiandev** [fabiandev/css-animator#10]
- [ ] Implement states for elements
- [ ] Add events (start, pause, resume, interrupt, end)
- [ ] Suggest to use interrupt event and to set `reject` option to `false`
- [ ] Probably use promise rejection on dispose for pending actions
- [ ] Keep track of all instances by a static member
- [ ] Think about saving the instance id on the element, to retrieve it (e.g. for setting listeners)
- [ ] Revisit browser compatibility check for CSS rules
- [ ] Think about the Angular2 service to return an instance (singleton) already
