### ISSUE TITLE
Next version roadmap (v2.0)

### ISSUE THREAD

**Issue by fabiandev** [fabiandev/css-animator#3]
- [x] Improve gulp tasks
- [x] Improve positioning and applied styles while animating
- [x] Fix flickering that sometimes occurs when animating with `show`
- [x] Performance improvements
- [x] Code cleanup
- [x] Look into staggering animation #6 (use promise of the animation builder to chain animations)
- [x] Ability to animate invisible elements and keep the space occupied #1 
- [x] Include source files (typings are included, for source files clone from git)
- [x] Rethink promise rejection if animation is aborted
- [x] Make available via next tag: `yarn add css-animator@next`
- [x] Merge to master
- [x] Release version [`v2.0.1`](https://github.com/fabiandev/css-animator/releases/tag/v2.0.1)
